source-tables:
  - "experiments-production"
  - "samples-production"

source-buckets:
  - "processed-matrix-production"
  - "biomage-source-production"

staging-experiments-table: "experiments-staging"
production-experiments-table: "experiments-production"
